In [38]:
import pandas as pd
import numpy as np

In [5]:
pd.__version__

'3.0.5'

In [9]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [10]:
df
9704
2
4
23.75
not change

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [11]:
df.sum

<bound method DataFrame.sum of       engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759
1                     130            5.0        97.0     3149.664934
2                     170            NaN        78.0     3079.038997
3                     220            4.0         NaN     2542.392402
4                     210            1.0       140.0     3460.870990
...                   ...            ...         ...             ...
9699                  140            5.0       164.0     2981.107371
9700                  180            NaN       154.0     2439.525729
9701                  220            2.0       138.0     2583.471318
9702                  230            4.0       177.0     2905.527390
9703                  270            3.0       140.0     2908.043477

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive
1             17.8        2007     USA  Gasoline  Front-wheel drive
2             15.1        2018  Europe  Gasoline  Front-wheel drive
3             20.2        2009     USA    Diesel    All-wheel drive
4             14.4        2009  Europe  Gasoline    All-wheel drive
...            ...         ...     ...       ...                ...
9699          17.3        2013  Europe    Diesel  Front-wheel drive
9700          15.0        2004     USA  Gasoline    All-wheel drive
9701          15.1        2008     USA    Diesel    All-wheel drive
9702          19.4        2011     USA    Diesel  Front-wheel drive
9703          14.7        2005    Asia    Diesel    All-wheel drive

      num_doors  fuel_efficiency_mpg
0           0.0            13.231729
1           0.0            13.688217
2           0.0            14.246341
3           2.0            16.912736
4           2.0            12.488369
...         ...                  ...
9699        NaN            15.101802
9700        0.0            17.962326
9701       -1.0            17.186587
9702        1.0            15.331551
9703       -1.0            14.884467

[9704 rows x 11 columns]>

In [15]:
df["fuel_type"].nunique()

2

In [20]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [25]:
df.fuel_efficiency_mpg[df.origin == "Asia"].max()

np.float64(23.759122836520497)

In [26]:
df.horsepower.median()

np.float64(149.0)

In [28]:
df.horsepower.value_counts().idxmax()

np.float64(152.0)

In [29]:
df.horsepower.fillna(152.0)

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [30]:
df.horsepower.median()

np.float64(149.0)

In [37]:
temp = df[df.origin == "Asia"]
temp1 = temp[["vehicle_weight", "model_year"]].head(n=7)
temp1

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [39]:
X = np.array(temp1)
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [45]:
XTX = X.T @ X

In [49]:
XTX_inv = np.linalg.inv(XTX)
print(np.linalg.cond(XTX))
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = XTX_inv @ X.T @ y
w

163.40615128004052

array([0.01386421, 0.5049067 ])

In [50]:
w.sum()

np.float64(0.5187709081074016)